# Generated by Django 4.2.7 on 2023-12-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_alter_blog_date_now_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comment_num',
            field=models.IntegerField(default=0, verbose_name='Yorum Sayısı'),
        ),
    ]
